---

- import_tasks: install.deb.yml
  when: ansible_os_family == 'Debian'

- import_tasks: install.yum.yml
  when: ansible_os_family == 'RedHat'

- file: state=directory name=/usr/share/python

- name: Install pip
  apt: name=python3-pip
  
- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3  

# https://stackoverflow.com/a/44456282/754432
# - pip:
#     virtualenv: /tmp/py3
#     virtualenv_command: /usr/bin/python3 -m venv

# - name: Update tools
#   pip: name="setuptools virtualenv" state=latest executable=pip{{item.item}}
#   environment:
#     PATH: "/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin"
#   when: item.changed
#   with_items: "{{ python_pip_installed.results }}"

- name: Install global python packages
  pip: name="{{python_install|join(' ')}}" executable={{python_pkg_bin}}/pip{{item}}
  when: python_install
  with_items: "{{ python_versions }}"

# - name: Install virtualenv
#   pip: name="virtualenv" executable={{python_pkg_bin}}/pip{{item}}
#   when: not( (python_virtualenvs is undefined) or (python_virtualenvs is none) or (python_virtualenvs | trim == '') )
#   with_items: "{{ python_versions }}"

- name: Setup virtualenvs
  shell: /usr/bin/python3 -m venv {{item.path}}
  args:
    creates: "{{item.path}}"
  with_items: "{{ python_virtualenvs }}"
  when: "python_virtualenv_user is not defined"

- name: Setup virtualenvs for specific user
  shell: "{{item.python|default('python')}} -m venv {{item.path}}"
  args:
    creates: "{{item.path}}"
  with_items: "{{ python_virtualenvs }}"
  become_user: "{{item.user|default(python_virtualenv_user)}}"
  when: "python_virtualenv_user is defined"

